SEND_ME_A_YOUTUBE_LINK = 'Send me a YouTube link'
COULD_BOT_GET_VIDEO = 'Could not get video'
DOES_NOT_LOOK_LIKE_A_YOUTUBE_LINK = 'Does not look like a YouTube link'
ERROR = 'Error'
CHOOSE_RESOLUTION = 'Please choose a resoultion'
FETCHING_DATA = 'Fetching data'